/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerfilIdRouteImport } from './routes/perfil.$id'
import { Route as EventoNovoRouteImport } from './routes/evento.novo'
import { Route as EventoIdRouteImport } from './routes/evento.$id'
import { Route as ClubeNovoRouteImport } from './routes/clube.novo'
import { Route as ClubeIdRouteImport } from './routes/clube.$id'
import { Route as CHandleRouteImport } from './routes/c.$handle'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIdRoute = PerfilIdRouteImport.update({
  id: '/perfil/$id',
  path: '/perfil/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoNovoRoute = EventoNovoRouteImport.update({
  id: '/evento/novo',
  path: '/evento/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoIdRoute = EventoIdRouteImport.update({
  id: '/evento/$id',
  path: '/evento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeNovoRoute = ClubeNovoRouteImport.update({
  id: '/clube/novo',
  path: '/clube/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeIdRoute = ClubeIdRouteImport.update({
  id: '/clube/$id',
  path: '/clube/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CHandleRoute = CHandleRouteImport.update({
  id: '/c/$handle',
  path: '/c/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/c/$handle': typeof CHandleRoute
  '/clube/$id': typeof ClubeIdRoute
  '/clube/novo': typeof ClubeNovoRoute
  '/evento/$id': typeof EventoIdRoute
  '/evento/novo': typeof EventoNovoRoute
  '/perfil/$id': typeof PerfilIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/c/$handle': typeof CHandleRoute
  '/clube/$id': typeof ClubeIdRoute
  '/clube/novo': typeof ClubeNovoRoute
  '/evento/$id': typeof EventoIdRoute
  '/evento/novo': typeof EventoNovoRoute
  '/perfil/$id': typeof PerfilIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/c/$handle': typeof CHandleRoute
  '/clube/$id': typeof ClubeIdRoute
  '/clube/novo': typeof ClubeNovoRoute
  '/evento/$id': typeof EventoIdRoute
  '/evento/novo': typeof EventoNovoRoute
  '/perfil/$id': typeof PerfilIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/onboarding'
    | '/c/$handle'
    | '/clube/$id'
    | '/clube/novo'
    | '/evento/$id'
    | '/evento/novo'
    | '/perfil/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/onboarding'
    | '/c/$handle'
    | '/clube/$id'
    | '/clube/novo'
    | '/evento/$id'
    | '/evento/novo'
    | '/perfil/$id'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/onboarding'
    | '/c/$handle'
    | '/clube/$id'
    | '/clube/novo'
    | '/evento/$id'
    | '/evento/novo'
    | '/perfil/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  CHandleRoute: typeof CHandleRoute
  ClubeIdRoute: typeof ClubeIdRoute
  ClubeNovoRoute: typeof ClubeNovoRoute
  EventoIdRoute: typeof EventoIdRoute
  EventoNovoRoute: typeof EventoNovoRoute
  PerfilIdRoute: typeof PerfilIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$id': {
      id: '/perfil/$id'
      path: '/perfil/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof PerfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/novo': {
      id: '/evento/novo'
      path: '/evento/novo'
      fullPath: '/evento/novo'
      preLoaderRoute: typeof EventoNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/$id': {
      id: '/evento/$id'
      path: '/evento/$id'
      fullPath: '/evento/$id'
      preLoaderRoute: typeof EventoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube/novo': {
      id: '/clube/novo'
      path: '/clube/novo'
      fullPath: '/clube/novo'
      preLoaderRoute: typeof ClubeNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube/$id': {
      id: '/clube/$id'
      path: '/clube/$id'
      fullPath: '/clube/$id'
      preLoaderRoute: typeof ClubeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$handle': {
      id: '/c/$handle'
      path: '/c/$handle'
      fullPath: '/c/$handle'
      preLoaderRoute: typeof CHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  CHandleRoute: CHandleRoute,
  ClubeIdRoute: ClubeIdRoute,
  ClubeNovoRoute: ClubeNovoRoute,
  EventoIdRoute: EventoIdRoute,
  EventoNovoRoute: EventoNovoRoute,
  PerfilIdRoute: PerfilIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
